#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d code web music discord 5 # VI VII VIII IX X

$HOME/.config/polybar/launch.sh main &

bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# bspc config border_radius 	     10%
bspc config border_width  	      0

bspc config normal_border_color "#ECEFF4"
bspc config focused_border_color "#05000B"


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
